<!-- Define Message -->
<input type="hidden" id="messageWaitSearch" name="messageWaitSearch" value="{{ __('Message_Waiting_Search') }}"/>
<input type="hidden" id="messageNoData" name="messageNoData" value="{{ __('Message_No_Data') }}"/>
<input type="hidden" id="messageNoSelectedData" name="messageNoSelectedData" value="{{ __('Message_No_Selected_Data') }}"/>
<input type="hidden" id="messageNoSelectedPattern" name="messageNoSelectedPattern" value="{{ __('Message_No_Selected_Pattern') }}"/>
<input type="hidden" id="messageAlarmEmptyTable" name="messageNoData" value="{{ __('Message_Alarm_Empty_Table') }}"/>
<input type="hidden" id="messageDelete" name="messageDelete" value="{{ __('Confirm_Delete') }}"/>
<input type="hidden" id="messageCopy" name="messageCopy" value="{{ __('Confirm_Copy') }}"/>
<input type="hidden" id="messageUserDelete" name="messageUserDelete" value="{{ __('User_Confirm_Delete') }}"/>
<input type="hidden" id="messageSystemError" name="messageSystemError" value="{{ __('Error_System') }}"/>
<input type="hidden" id="messageAddEmployeeError" name="messageAddEmployeeError" value="{{ __('Deparment_Count_Employee') }}"/>
<input type="hidden" id="titlePDF" name="titlePDF" value="{{ __('SkillMap_PDF_Title') }}"/>
<input type="hidden" id="timeOutPDF" name="timeOutPDF" value="{{ __('SkillMap_TimeOut') }}"/>
<input type="hidden" id="messageSkillMapRequired" name="messageSkillMapRequired" value="{{ __('SkillMap_Err_Required') }}"/>
<input type="hidden" id="messageSkillMapFormatNumber" name="messageSkillMapFormatNumber" value="{{ __('SkillMap_Err_FormatNumber') }}"/>
<input type="hidden" id="messageSkillMapMaxLength" name="messageSkillMapMaxLength" value="{{ __('SkillMap_MaxLength') }}"/>
<input type="hidden" id="messageCompanyFreeContract" name="messageCompanyFreeContract" value="{{ __('Company_Free_Contract') }}"/>
<input type="hidden" id="messageCompanyPaidContract" name="messageCompanyPaidContract" value="{{ __('Company_Paid_Contract') }}"/>
<input type="hidden" id="confirmMessage" name="confirmMessage" value="{{ __('Pattern_Confirm_Message') }}"/>
<input type="hidden" id="unBindDeptPatternMsg" name="unBindDeptPatternMsg" value="{{ __('Pattern_Unbind_Confirm_Message') }}"/>
<input type="hidden" id="bindDeptPatternMsg" name="bindDeptPatternMsg" value="{{ __('Pattern_Bind_Confirm_Message') }}"/>
<input type="hidden" id="errMessageUse1Pattern" name="errMessageUse1Pattern" value="{{ __('Pattern_Err_Use_Only_1_Pattern') }}"/>
<input type="hidden" id="patternAtLeastOneVerificationPointMustBeConfigured" name="patternAtLeastOneVerificationPointMustBeConfigured" value="{{ __('Pattern_At_Least_One_Verification_Point_Must_Be_Configured') }}"/>
<input type="hidden" id="messagePatternRequired" name="messagePatternRequired" value="{{ __('Pattern_Err_Required') }}"/>
<input type="hidden" id="messagePatternFormatNumber" name="messagePatternFormatNumber" value="{{ __('Pattern_Err_FormatNumber') }}"/>
<input type="hidden" id="placeHolderPoint" name="placeHolderPoint" value="{{ __('Pattern_Detail_Num_Point') }}"/>
<input type="hidden" id="kaizenbaseID" name="kaizenbaseID" value="{{Constant::KAIZEN_BASE_COMPANY_ID}}"/>
<input type="hidden" id="radarLabel" name="radarLabel" value="{{ __('TopPage_Radar_Label') }}"/>
<input type="hidden" id="commonDepartment" name="commonDepartment" value="{{ __('Department') }}"/>
<input type="hidden" id="existedImage" name="existedImage" value="{{ __('Evidence_Existed_Image') }}"/>
<input type="hidden" id="noFileUpload" name="noFileUpload" value="{{ __('Evidence_No_File_To_Upload') }}"/>
<input type="hidden" id="noImage" name="noImage" value="{{Constant::NO_IMAGE_PATH}}"/>
<input type="hidden" id="registeredInspectionId" name="registeredInspectionId" value="{{ __('TeamInspection_Registered') }}"/>
<input type="hidden" id="confirmDeleteMsgId" name="confirmDeleteMsgId" value="{{ __('Common_Are_You_Sure_Delete') }}"/>
<input type="hidden" id="confirmSaveMsgId" name="confirmSaveMsgId" value="{{ __('Confirm_Message_Save_Data') }}"/>
<input type="hidden" id="closeDialogMsgId" name="closeDialogMsgId" value="{{ __('Evidence_Close_Dialog_Warning') }}"/>
<input type="hidden" id="onlyOneBlockForFreeAccId" name="onlyOneBlockForFreeAccId" value="{{ __('Evidence_Only_One_Block_For_Free') }}"/>
<input type="hidden" id="deleteMsgTooltipId" name="deleteMsgTooltipId" value="{{ __('Evidence_Delete_Image_Tooltip') }}"/>
<input type="hidden" id="messageChoosePatternForThisDepartment" name="messageChoosePatternForThisDepartment" value="{{ __('TeamInspection_Please_Choose_Pattern_For_This_Department') }}"/>
<input type="hidden" id="changeDeptWarningMsgId" name="changeDeptWarningMsgId" value="{{ __('Pattern_Change_Department_Warning') }}"/>
<input type="hidden" id="changeBindedDeptWarningMsgId" name="changeBindedDeptWarningMsgId" value="{{ __('Pattern_Change_Binded_Department_Warning') }}"/>
<input type="hidden" id="noSelectedBlock" name="noSelectedBlock" value="{{ __('Evidence_No_Selected_Block') }}"/>
<input type="hidden" id="unsavedDataWarning" name="unsavedDataWarning" value="{{ __('Common_Unsaved_Data_Warning') }}"/>
<input type="hidden" id="savePatternMsgId" name="savePatternMsgId" value="{{ __('Pattern_Label_Modal_Save_Pattern') }}"/>
<input type="hidden" id="deletePatternWarningMsg" name="deletePatternWarningMsg" value="{{ __('Pattern_Delete_Warning') }}"/>
<input type="hidden" id="noTeamInDeptWarning" name="noTeamInDeptWarning" value="{{ __('TeamInspection_Please_Create_Team_This_Department1') }}"/>
<input type="hidden" id="deleteLastInspectionWarningMsg" name="deleteLastInspectionWarningMsg" value="{{ __('TeamInspection_Delete_Last_Inspection_Warning') }}"/>
<input type="hidden" id="requiredPatterNameErrMsg" name="requiredPatterNameErrMsg" value="{{ __('Pattern_Adding_A_Pattern_Name_Is_Mandatory') }}"/>
<input type="hidden" id="common5sFreeBadgeId" name="common5sFreeBadgeId" value="{{ __('Common_5S_Free_Badge') }}"/>
<input type="hidden" id="commonSkillMapFreeBadgeId" name="commonSkillMapFreeBadgeId" value="{{ __('Common_SkillMap_Free_Badge') }}"/>
<input type="hidden" id="commonFreeBadgeId" name="commonFreeBadgeId" value="{{ __('Common_Free_Badge') }}"/>
<input type="hidden" id="commonFreeBadge1Id" name="commonFreeBadge1Id" value="{{ __('Common_Free_Badge_1') }}"/>
<input type="hidden" id="titleAccountDialog" name="titleAccountDialog" value="{{ __('Account') }}"/>
<input type="hidden" id="titleDepartmentDialog" name="titleDepartmentDialog" value="{{ __('Department') }}"/>
<input type="hidden" id="titleTeamDialog" name="titleTeamDialog" value="{{ __('Team') }}"/>
<input type="hidden" id="titleEmployeeDialog" name="titleEmployeeDialog" value="{{ __('Employee') }}"/>
<input type="hidden" id="titleSkillmapDialog" name="titleSkillmapDialog" value="{{ __('SkillMap_Label') }}"/>
<input type="hidden" id="deleteLabel" name="deleteLabel" value="{{ __('Common_Delete_Label') }}"/>
<input type="hidden" id="skillMapCopyDialogLabel" name="skillMapCopyDialogLabel" value="{{ __('SkillMap_Copy_Dialog_Label') }}"/>
<input type="hidden" id="editDialogButtonOK" name="editDialogButtonOK" value="{{ __('Common_button_ok_save') }}"/>
<input type="hidden" id="addDialogButtonOK" name="addDialogButtonOK" value="{{ __('Common_button_ok_add_dialog') }}"/>
<input type="hidden" id="confirmMsgId" name="confirmMsgId" value="{{ __('Common_Confirm') }}"/>
