<!-- Define Message -->
<input type="hidden" id="messageWaitSearch" name="messageWaitSearch" value="{{ __('Message_Waiting_Search') }}"/>
<input type="hidden" id="messageNoData" name="messageNoData" value="{{ __('Message_No_Data') }}"/>
<input type="hidden" id="messageNoSelectedData" name="messageNoSelectedData" value="{{ __('Message_No_Selected_Data') }}"/>
<input type="hidden" id="messageAlarmEmptyTable" name="messageNoData" value="{{ __('Message_Alarm_Empty_Table') }}"/>
<input type="hidden" id="messageDelete" name="messageDelete" value="{{ __('Confirm_Delete') }}"/>
<input type="hidden" id="messageCopy" name="messageCopy" value="{{ __('Confirm_Copy') }}"/>
<input type="hidden" id="messageUserDelete" name="messageUserDelete" value="{{ __('User_Confirm_Delete') }}"/>
<input type="hidden" id="messageSystemError" name="messageSystemError" value="{{ __('Error_System') }}"/>
<input type="hidden" id="messageAddEmployeeError" name="messageAddEmployeeError" value="{{ __('Deparment_Count_Employee') }}"/>
<input type="hidden" id="titlePDF" name="titlePDF" value="{{ __('SkillMap_PDF_Title') }}"/>
<input type="hidden" id="timeOutPDF" name="timeOutPDF" value="{{ __('SkillMap_TimeOut') }}"/>
<input type="hidden" id="messageSkillMapRequired" name="messageSkillMapRequired" value="{{ __('SkillMap_Err_Required') }}"/>
<input type="hidden" id="messageSkillMapFormatNumber" name="messageSkillMapFormatNumber" value="{{ __('SkillMap_Err_FormatNumber') }}"/>
<input type="hidden" id="messageSkillMapMaxLength" name="messageSkillMapMaxLength" value="{{ __('SkillMap_MaxLength') }}"/>
<input type="hidden" id="messageCompanyFreeContract" name="messageCompanyFreeContract" value="{{ __('Company_Free_Contract') }}"/>
<input type="hidden" id="messageCompanyPaidContract" name="messageCompanyPaidContract" value="{{ __('Company_Paid_Contract') }}"/>
<input type="hidden" id="confirmMessage" name="confirmMessage" value="{{ __('Common_Confirm_Message') }}"/>
<input type="hidden" id="patternAtLeastOneVerificationPointMustBeConfigured" name="patternAtLeastOneVerificationPointMustBeConfigured" value="{{ __('Pattern_At_Least_One_Verification_Point_Must_Be_Configured') }}"/>
